"""add sets

Revision ID: 9617e1015e97
Revises: f53bda5e3cce
Create Date: 2026-01-02 23:45:59.893645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9617e1015e97"
down_revision: Union[str, Sequence[str], None] = "f53bda5e3cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("rpe", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"], ["workout_exercises.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workout_exercise_id",
            "set_index",
            name="uq_sets_workout_exercise_set_index",
        ),
    )
    op.create_index(
        op.f("ix_sets_workout_exercise_id"),
        "sets",
        ["workout_exercise_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sets_workout_exercise_id"), table_name="sets")
    op.drop_table("sets")
    # ### end Alembic commands ###
