"""add exercises

Revision ID: b11f6d068088
Revises: cc6ab6381a2a
Create Date: 2026-01-01 23:32:56.318585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11f6d068088'
down_revision: Union[str, Sequence[str], None] = 'cc6ab6381a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_muscle', sa.Enum('chest', 'back', 'triceps', 'biceps', 'abs', 'legs', name='exercise_muscle'), nullable=False),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'machine', 'cable', 'kettlebell', 'bodyweight', 'other', name='exercise_equipment'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
