"""add workout_exercises

Revision ID: f53bda5e3cce
Revises: 08936af694cd
Create Date: 2026-01-02 23:43:36.168949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f53bda5e3cce"
down_revision: Union[str, Sequence[str], None] = "08936af694cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workout_id", "position", name="uq_workout_exercises_workout_id_position"
        ),
    )
    op.create_index(
        op.f("ix_workout_exercises_exercise_id"),
        "workout_exercises",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workout_exercises_workout_id"),
        "workout_exercises",
        ["workout_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workout_exercises_workout_id"), table_name="workout_exercises"
    )
    op.drop_index(
        op.f("ix_workout_exercises_exercise_id"), table_name="workout_exercises"
    )
    op.drop_table("workout_exercises")
    # ### end Alembic commands ###
